import React from 'react'
import Navbar from '../components/Navbar'
import { Typography, Stack, Grid, Box, IconButton, useMediaQuery, CssBaseline } from '@mui/material'
import { createTheme, ThemeProvider } from '@mui/material/styles';
import OpenInBrowserIcon from '@mui/icons-material/OpenInBrowser';
import GoogleIcon from '@mui/icons-material/Google';
import backgroundImage from '../images/cyp.png'
// import useWindowDimensions from '../components/Window';
import PeopleCard from '../components/PeopleCard';

const people1 = {
    name: 'Joe Doe',
    programTitle: 'Bachelor of Science in',
    program: 'Computer Science',
    image: 'https://www.broadlawns.org/filesimages/No%20Image.jpg',
    detail: 'abshcuihiejslkac'
};
const people2 = {
  name: 'Joe Doe',
  programTitle: "Ph.D. Candidate in",
  program: 'Computer Science',
  image: 'https://www.broadlawns.org/filesimages/No%20Image.jpg',
  detail: 'abshcuihiejslkac'
};
const people3 = {
  name: 'Joe Doe',
  programTitle: "Ph.D. Student in",
  program: 'Computer Science',
  image: 'https://www.broadlawns.org/filesimages/No%20Image.jpg',
  detail: 'abshcuihiejslkac'
};

function People() {
  // const { height, width } = useWindowDimensions();
  const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)');
  const theme = React.useMemo(
      () =>
          createTheme({
              palette: {
                  mode: prefersDarkMode ? 'dark' : 'light',
              },
          }),
      [prefersDarkMode],
  );
   
  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <Stack
        direction="column"
        justifyContent="space-evenly"
        alignItems="center"
        spacing={2}
        sx={{
          backgroundImage: `url(${backgroundImage})`,
          width: '100%',
          height:'300px',
          backgroundSize: 'cover',
          backgroundPosition: 'center',}}
      >
        <Navbar/>
        <Typography variant="h2" sx={{alignContent:'center', color:'#ffffff'}}>
          Our Team
        </Typography>
      </Stack>
      <Box sx={{ flexGrow: 1 }}>
        <Grid container
              spacing={1}
              direction="row"
              justifyContent="center"
              alignItems="center"
              width="90%"
              sx={{m:'auto', mt:5}}>
          <Grid item xs={12}>
            <Typography variant="h4" align='center' sx={{m: 'auto', mb:2}}>
              Principal Investigator
            </Typography>
          </Grid>
          <Grid item xs={12} sm={6} sx={{mt: 1}}>
              <img 
              src="https://www.cs.ubc.ca/~jiaruid/images/jiarui.jpg" 
              alt='NA' 
              style={{width:"50%", display: "block", "marginLeft": "auto", "marginRight": "auto"}}>
              </img>
          </Grid>
          <Grid item xs={12} sm={6}>
            <Typography variant='h4' align='left'>
              Dr. Jiarui Ding
            </Typography>
            <Typography variant='h5' align='left' sx={{mt:5}}>
              Personal Website: {<IconButton onClick={()=>{window.open("https://www.cs.ubc.ca/~jiaruid/index.html", '_blank');}}><OpenInBrowserIcon/></IconButton>}
            </Typography>
            <Typography variant='h5' align='left'>
              Google Scholar: {<IconButton onClick={()=>{window.open("https://scholar.google.ca/citations?user=AtFiBlgAAAAJ&hl=en", '_blank');}}><GoogleIcon/></IconButton>}
            </Typography>
            <Typography variant='h5' align='left' sx={{mt:3}}>
              Research Interest:
            </Typography>
            <Typography variant='body' align='left'>
              {"My research focuses on developing statistical models and efficient algorithms to learn biologically interpretable latent structures in large-scale, high-dimensional single-cell genomics data, such as those from single-cell transcriptomics, single-cell epigenomics, and spatially resolved methods. I’m interested in integrating these datasets generated by cutting-edge single-cell genomics technologies to provide a comprehensive view of biological systems, and understand how they change dynamically under disease perturbations (e.g., cancer and allergic diseases) and treatments. I’m also interested in technology development and analyzing the features of data generated by different platforms for developing effective data analysis tools (with Dr. Joshua Levin)."}
            </Typography>
          </Grid>
          <Grid item xs={12}>
            <Typography variant="h4" align='center' sx={{m: 'auto', mt:10}}>
              Team Members
            </Typography>
          </Grid>
          <Grid item xs={12} sm={6} md={3} align='center' sx={{mt: 1}}>
            <PeopleCard people={people1}/>
          </Grid>
          <Grid item xs={12} sm={6} md={3} align='center' sx={{mt: 1}}>
            <PeopleCard people={people2}/>
          </Grid>
          <Grid item xs={12} sm={6} md={3} align='center' sx={{mt: 1}}>
            <PeopleCard people={people3}/>
          </Grid>
          <Grid item xs={12} sm={6} md={3} align='center' sx={{mt: 1}}>
            <PeopleCard people={people1}/>
          </Grid>
          <Grid item xs={12} sm={6} md={3} align='center' sx={{mt: 1}}>
            <PeopleCard people={people1}/>
          </Grid>
        </Grid>
      </Box>
    </ThemeProvider>
  )
}

export default People